config:
  ignore:
    paths:
      - /api/public/index2.php
    commits:
      - 130af3f2fa6ea746e4358bf9f973510417457813
    file_extensions:
      - md
techstack:
  devops:
    - kubernetes
    - fluxcd
    - docker
